name: xcelera performance audit
description: Perform a performance audit of a GitHub repository
author: xcelera.dev

branding:
  icon: lightning
  color: yellow

inputs:
  url:
    description: The URL of the web page to audit
    required: true

outputs:
  result:
    description: The result of the audit request

runs:
  using: node20
  main: dist/index.js
