name: xcelera performance audit
description:
  Perform a performance audit of a web page using Xcelera's Lighthouse testing
  service
author: xcelera.dev

branding:
  icon: zap
  color: yellow

inputs:
  url:
    description: The URL of the web page to audit
    required: true
  token:
    description: Xcelera API token for authentication
    required: true
  auth:
    description: Full auth config as JSON string (for authenticated pages)
    required: false
  cookie-file:
    description: Path to a Netscape cookie file (cookies.txt) (for authenticated pages)
    required: false
  cookie:
    description: Cookie in "name=value" format (for authenticated pages)
    required: false
  header:
    description: 'Header in "Name: Value" format (for authenticated pages)'
    required: false

outputs:
  auditId:
    description: The ID of the scheduled test
  status:
    description: The status of the audit request (scheduled, failed)
  error:
    description: The error message if the audit request fails

runs:
  using: node20
  main: dist/action.js
